/**
 * The one test ticket 25 stands on: **every move the engine offers is reachable
 * through a click path**, over a corpus of real positions from real games.
 *
 * A UI can be wrong in two directions. It can offer something illegal, which
 * the engine catches by throwing - `apply` re-validates everything, so that
 * failure mode is loud and cheap. The dangerous direction is the other one: a
 * move that is legal and simply cannot be clicked. Nothing throws, nothing
 * looks broken, and a card quietly never gets played for the rest of the
 * project. So the assertion here is coverage, checked by driving the SAME
 * resolvers the interface uses rather than by re-deriving what should be
 * clickable.
 *
 * The corpus is generated by walking games with the bots, collecting every
 * position where a decision was taken. That is deliberately not a fixture:
 * a fixture would age against the rules, and this way a card added in the sheet
 * shows up in the corpus on the next run.
 */

import { describe, expect, it } from 'vitest';
import { BASE_GAME_DATA as data } from '@gp/data';
import type { Suit } from '@gp/data';
import { MOVE_TYPES, apply, isOver, legalMoves, makeProber, newGame, viewFor } from '@gp/engine';
import type { Move, MoveType, PlayerView } from '@gp/engine';
import { makePolicy, policyRng } from '@gp/bots';

import {
  MOVE_ROUTES,
  buildCandidates,
  buildComplete,
  clickBalloon,
  clickBuilding,
  clickDeck,
  clickRival,
  clickTile,
  clickWorker,
  emptyBuildDraft,
  liveTargets,
  subsetAnswer,
  visitOffers,
  visitPayoffs,
  withStackPayment,
  withPayment,
} from './intent';
import type { BuildDraft, Intent } from './intent';
import { actionGroups } from './moveText';

const IDLE: Intent = { k: 'idle' };

interface Position {
  readonly view: PlayerView;
  readonly moves: Move[];
}

/**
 * Walk seeded games and keep every decision point, from every seat's point of
 * view. `viewFor(actor)` rather than always seat 0: the interface is written
 * from one chair, but the click resolvers must work for whichever chair is
 * being asked, and a task belonging to another seat is exactly the case that
 * would otherwise go untested.
 */
function corpus(seeds: readonly string[], seats: number, suits: Suit[]): Position[] {
  const out: Position[] = [];
  for (const seed of seeds) {
    let state = newGame(data, { seats, suits, seed });
    const rngs = new Map<number, ReturnType<typeof policyRng>>();
    for (let s = 0; s < seats; s++) rngs.set(s, policyRng(seed, s, 'balanced'));
    for (let step = 0; step < 900 && !isOver(state); step++) {
      const moves = legalMoves(data, state);
      if (moves.length === 0) break;
      const actor = state.tasks[0]?.pid ?? state.turnPlayer;
      const view = viewFor(data, state, actor);
      out.push({ view, moves });
      const policy = makePolicy(step % 3 === 0 ? 'pulse' : 'balanced');
      const rng = rngs.get(actor) ?? policyRng(seed, actor, 'balanced');
      const probe = makeProber(data, state, actor);
      state = apply(data, state, policy.choose({ data, view, moves, rng, probe })).state;
    }
  }
  return out;
}

/** Does some click path produce this exact move object? */
function reachable(position: Position, move: Move): boolean {
  const { moves } = position;
  const has = (candidates: readonly Move[]) => candidates.includes(move);

  switch (move.type) {
    case 'draw':
    case 'pass':
    case 'endTurn':
    case 'cardMove':
      // The action bar hands its whole family straight to `choose`.
      return moves.filter((m) => m.type === move.type).includes(move);

    case 'harvest':
    case 'upgrade':
    case 'grow': {
      const held: Intent = move.type === 'grow' ? { k: 'hold', card: move.payment } : IDLE;
      return has(clickBuilding(moves, held, move.type === 'grow' ? move.building : cardOf(move)));
    }

    case 'buy':
    case 'market':
      return has(clickDeck(moves, IDLE, move.suit));

    case 'deliver':
      return has(clickTile(moves, IDLE, move.tile));

    case 'moveBalloon':
      return has(clickBalloon(moves, IDLE, move.balloon));

    case 'workOwnWorker':
      return has(clickWorker(moves, IDLE, move.workerId));

    case 'build': {
      // The panel: name the card, then add payment one click at a time.
      const assembled = assembleBuild(moves, move.card, move.payment, []);
      return assembled?.move === move;
    }

    case 'visit': {
      // The panel: pick the host, add fee cards, then take a payoff.
      if (clickRival(moves, IDLE, move.host) === null) return false;
      const draft = { host: move.host, fee: move.fee };
      if (visitOffers(moves, draft).length === 0) return false;
      return visitPayoffs(moves, draft).includes(move);
    }

    case 'task':
      return taskReachable(position, move);

    default:
      return move satisfies never;
  }
}

function cardOf(move: Move): string {
  if (move.type === 'harvest') return move.building;
  if (move.type === 'upgrade') return move.card;
  throw new Error('not a building move');
}

/** Replay the build panel's clicks for a known target payment. */
function assembleBuild(
  moves: readonly Move[],
  card: string,
  payment: readonly string[],
  stacks: readonly string[],
): ReturnType<typeof buildComplete> {
  let draft: BuildDraft = emptyBuildDraft(card);
  for (const paid of payment) {
    draft = withPayment(draft, paid);
    if (buildCandidates(moves, draft).length === 0) return null;
  }
  for (const paid of stacks) {
    draft = withStackPayment(draft, paid);
    if (buildCandidates(moves, draft).length === 0) return null;
  }
  return buildComplete(moves, draft);
}

/**
 * The build panel has to be OPENABLE, not merely completable.
 *
 * A build TASK (W7 Golden Field's harvest, the Build Worker) is the one task
 * with no in-place gesture: its answer names a card in the HAND, and a hand
 * click otherwise means "pick up". Assembling from a draft the test made itself
 * proved nothing about how a player gets that draft - which is how the panel
 * stayed dead behind a prompt that said "Build a card from your hand" while
 * this file was green. Both doors are checked: the action bar's Build family
 * must list the task's moves, and the card must be lit for the click that opens
 * the assembly.
 */
function buildPanelOpens(position: Position, card: string): boolean {
  const armed: Intent = { k: 'arm', type: 'build' };
  const bar = actionGroups(position.moves).find((g) => g.type === 'build');
  if (!bar || bar.moves.length === 0) return false;
  return liveTargets(position.view, position.moves, armed).hand.has(card);
}

function taskReachable(position: Position, move: Move): boolean {
  if (move.type !== 'task') return false;
  const { moves } = position;
  const answer = move.answer;
  switch (answer.kind) {
    case 'deck':
      return clickDeck(moves, IDLE, answer.suit).includes(move);
    case 'building':
      return clickBuilding(moves, IDLE, answer.card).includes(move);
    case 'sow':
      return clickBuilding(moves, { k: 'hold', card: answer.card }, answer.onto).includes(move);
    case 'worker':
      return clickWorker(moves, IDLE, answer.workerId).includes(move);
    case 'deliver':
      return clickTile(moves, IDLE, answer.tile).includes(move);
    case 'balloon':
      return clickBalloon(moves, IDLE, answer.balloon).includes(move);
    case 'build':
      return (
        buildPanelOpens(position, answer.card) &&
        assembleBuild(moves, answer.card, answer.payment, answer.stacks ?? [])?.move === move
      );
    case 'keep':
      return subsetAnswer(moves, 'keep', answer.cards) === move;
    case 'discard':
      return subsetAnswer(moves, 'discard', answer.cards) === move;
    case 'deckSow':
    case 'handToBarn':
    case 'skip':
    case 'card':
      // The prompt lists these explicitly; nothing to resolve.
      return moves.includes(move);
    default:
      return answer satisfies never;
  }
}

const SEEDS = ['click-a', 'click-b'];

describe('every legal move is reachable through the interface', () => {
  const tables: { name: string; positions: Position[] }[] = [
    { name: '2 seats', positions: corpus(SEEDS, 2, ['wheat', 'orchard']) },
    { name: '3 seats', positions: corpus(SEEDS, 3, ['wheat', 'vegetable', 'orchard']) },
    {
      name: '4 seats',
      positions: corpus(['click-c'], 4, ['wheat', 'vegetable', 'apiary', 'dairy']),
    },
  ];

  for (const { name, positions } of tables) {
    it(`at ${name}`, () => {
      expect(positions.length).toBeGreaterThan(200);
      const unreachable: string[] = [];
      for (const position of positions) {
        for (const move of position.moves) {
          if (!reachable(position, move)) {
            unreachable.push(
              `${move.type}${move.type === 'task' ? `/${move.answer.kind}` : ''}: ${JSON.stringify(move)}`,
            );
          }
        }
      }
      expect([...new Set(unreachable)].slice(0, 5)).toEqual([]);
    });
  }

  it('actually meets a build task, so its two doors are really being checked', () => {
    const tasks = tables.flatMap(({ positions }) =>
      positions.flatMap((p) =>
        p.moves.filter((m) => m.type === 'task' && m.answer.kind === 'build'),
      ),
    );
    expect(tasks.length).toBeGreaterThan(0);
  });

  it('exercises every move type across the corpus, so the coverage means something', () => {
    const seen = new Set<MoveType>();
    for (const { positions } of tables) {
      for (const position of positions) {
        for (const move of position.moves) seen.add(move.type);
      }
    }
    // `pass` is the one type a healthy game may never reach: it exists only for
    // a turn with no legal main action at all.
    const missing = MOVE_TYPES.filter((t) => !seen.has(t) && t !== 'pass');
    expect(missing).toEqual([]);
  });
});

describe('the route table cannot drift from the engine', () => {
  it('routes every move type the engine can offer', () => {
    expect(Object.keys(MOVE_ROUTES).sort()).toEqual([...MOVE_TYPES].sort());
  });
});

describe('what glows', () => {
  const positions = corpus(['glow'], 3, ['wheat', 'vegetable', 'orchard']);

  it('lights nothing when there is nothing to do', () => {
    const first = positions[0] as Position;
    const live = liveTargets(first.view, [], IDLE);
    expect(live.buildings.size + live.hosts.size + live.tiles.size + live.hand.size).toBe(0);
  });

  it('never lights a target whose click resolves to nothing', () => {
    for (const { view, moves } of positions) {
      const live = liveTargets(view, moves, IDLE);
      for (const card of live.buildings) {
        expect(clickBuilding(moves, IDLE, card).length).toBeGreaterThan(0);
      }
      for (const tile of live.tiles) expect(clickTile(moves, IDLE, tile).length).toBeGreaterThan(0);
      for (const seat of live.hosts) expect(clickRival(moves, IDLE, seat)).not.toBeNull();
    }
  });

  it('narrows the hand to the payment while a build is being assembled', () => {
    const withBuild = positions.find((p) => p.moves.some((m) => m.type === 'build'));
    expect(withBuild).toBeDefined();
    const build = (withBuild as Position).moves.find((m) => m.type === 'build') as Extract<
      Move,
      { type: 'build' }
    >;
    const intent: Intent = { k: 'build', draft: emptyBuildDraft(build.card) };
    const live = liveTargets((withBuild as Position).view, (withBuild as Position).moves, intent);
    // The card being built never pays for itself, and nothing else on the table
    // is a target while a payment is open.
    expect(live.hand.has(build.card)).toBe(false);
    expect(live.buildings.size).toBe(0);
    expect(live.tiles.size).toBe(0);
  });

  it('lights only the host being visited once a visit is open', () => {
    const withVisit = positions.find((p) => p.moves.some((m) => m.type === 'visit'));
    expect(withVisit).toBeDefined();
    const visit = (withVisit as Position).moves.find((m) => m.type === 'visit') as Extract<
      Move,
      { type: 'visit' }
    >;
    const live = liveTargets((withVisit as Position).view, (withVisit as Position).moves, {
      k: 'visit',
      host: visit.host,
      fee: [],
    });
    expect([...live.hosts]).toEqual([visit.host]);
  });
});
