/**
 * The one test ticket 25 stands on: **every move the engine offers is reachable
 * through a click path**, over a corpus of real positions from real games.
 *
 * A UI can be wrong in two directions. It can offer something illegal, which
 * the engine catches by throwing - `apply` re-validates everything, so that
 * failure mode is loud and cheap. The dangerous direction is the other one: a
 * move that is legal and simply cannot be clicked. Nothing throws, nothing
 * looks broken, and a card quietly never gets played for the rest of the
 * project. So the assertion here is coverage, checked by driving the SAME
 * resolvers the interface uses rather than by re-deriving what should be
 * clickable.
 *
 * The corpus is generated by walking games with the bots, collecting every
 * position where a decision was taken. That is deliberately not a fixture:
 * a fixture would age against the rules, and this way a card added in the sheet
 * shows up in the corpus on the next run.
 */

import { describe, expect, it } from 'vitest';
// ⛔ THE UI'S OWN DATA, NOT `BASE_GAME_DATA`, since 04/09/2026. `session/table.ts`
// used to pin itself to the pre-notice-board v31 arm; the pin came down
// 18/09/2026 and this now loads the same shipped `loadGameData()` defaults the
// engine, the bots and the simulator play, with one override (no hand limit -
// see the docblock on `session/table.ts`). A test importing `data` from here is
// exercising the shipped game, not an arm.
import { data } from '../session/table';
import type { Suit } from '@gp/data';
import { MOVE_TYPES, apply, isOver, legalMoves, makeProber, newGame, viewFor } from '@gp/engine';
import type { CardId, Move, MoveType, PlayerView } from '@gp/engine';
import { makePolicy, policyRng } from '@gp/bots';

import {
  MOVE_ROUTES,
  UNROUTED_TASK_ANSWERS,
  buildCandidates,
  buildComplete,
  clickBuilding,
  clickCardPower,
  clickDeck,
  clickHandCard,
  clickHost,
  clickMeeple,
  clickTile,
  emptyBuildDraft,
  liveTargets,
  subsetAnswer,
  visitBoards,
  visitComplete,
  visitOffers,
  withStackPayment,
  withPayment,
} from './intent';
import type { BuildDraft, Intent, VisitDraft } from './intent';
import { actionGroups } from './moveText';

const IDLE: Intent = { k: 'idle' };

interface Position {
  readonly view: PlayerView;
  readonly moves: Move[];
}

/**
 * Walk seeded games and keep every decision point, from every seat's point of
 * view. `viewFor(actor)` rather than always seat 0: the interface is written
 * from one chair, but the click resolvers must work for whichever chair is
 * being asked, and a task belonging to another seat is exactly the case that
 * would otherwise go untested.
 */
function corpus(seeds: readonly string[], seats: number, suits: Suit[]): Position[] {
  const out: Position[] = [];
  for (const seed of seeds) {
    let state = newGame(data, { seats, suits, seed });
    const rngs = new Map<number, ReturnType<typeof policyRng>>();
    for (let s = 0; s < seats; s++) rngs.set(s, policyRng(seed, s, 'balanced'));
    for (let step = 0; step < 900 && !isOver(state); step++) {
      const moves = legalMoves(data, state);
      if (moves.length === 0) break;
      const actor = state.tasks[0]?.pid ?? state.turnPlayer;
      const view = viewFor(data, state, actor);
      out.push({ view, moves });
      const policy = makePolicy(step % 3 === 0 ? 'pulse' : 'balanced');
      const rng = rngs.get(actor) ?? policyRng(seed, actor, 'balanced');
      const probe = makeProber(data, state, actor);
      state = apply(data, state, policy.choose({ data, view, moves, rng, probe })).state;
    }
  }
  return out;
}

/** Does some click path produce this exact move object? */
function reachable(position: Position, move: Move): boolean {
  const { moves } = position;
  const has = (candidates: readonly Move[]) => candidates.includes(move);

  switch (move.type) {
    case 'draw':
    case 'bonusDraw':
    case 'pass':
    case 'endTurn':
      // The turn bar hands its whole family straight to `choose`.
      return moves.filter((m) => m.type === move.type).includes(move);

    /*
     * ⭐ ON THE PAWN, NOT ON THE BAR (v31). Spending a meeple is done on the
     * meeple in your own supply, so the check is the same two-part one the card
     * powers get: the resolver answers, AND the seat really holds a meeple of
     * that colour for the supply strip to have drawn. Without the second half
     * the pawn could be drawn nowhere at all and this would still pass.
     */
    case 'spendMeeple':
      return (
        (position.view.you.meeples[move.colour] ?? 0) > 0 && has(clickMeeple(moves, move.colour))
      );

    /*
     * ON THE CARD SINCE 26/08/2026, so the check is no longer "is it in the
     * list" - it is "is the card that offers it on the board in front of this
     * seat". Without that second half the badge could be drawn nowhere at all
     * and this would still pass, which is exactly the silent failure the file
     * exists to catch: the resolver would answer, and nothing would ask it.
     */
    case 'cardMove':
      return (
        position.view.you.tableau.some((b) => b.card === move.card) &&
        has(clickCardPower(moves, move.card))
      );

    case 'harvest':
    case 'grow': {
      // A meeple-paid GROW (R15) holds no card, so it falls back to IDLE.
      const held: Intent =
        move.type === 'grow' && move.payment !== null ? { k: 'hold', card: move.payment } : IDLE;
      return has(clickBuilding(moves, held, move.type === 'grow' ? move.building : move.building));
    }

    case 'deliver':
      return has(clickTile(moves, IDLE, move.tile));

    case 'build': {
      // The panel: name the card, then add payment one click at a time.
      const assembled = assembleBuild(moves, move.card, move.payment, []);
      return assembled?.move === move;
    }

    /*
     * ⭐ THE HOST AND ITS BOARD, BOTH CLICKED (18/09/2026, 2.2.1). At two
     * players a rival may hold TWO Notice Boards, and two boards mean two
     * different powers - so a draft that never named one could still narrow to
     * more than one surviving move, and the wrong one could win by chance.
     * `move.board` is what `visitBoards` lists as the choice on offer; passing
     * it through here (both to `clickHost`, which the panel calls first to open
     * on this host, and into the draft `visitOffers`/`visitComplete` narrow) is
     * what makes a two-board host's move provably reachable rather than merely
     * plausible. Self-visiting is banned under the shipped rules (11/09/2026),
     * so `move.host` is never `move.seat` in any corpus this file builds.
     */
    case 'visit': {
      if (clickHost(position.view, moves, IDLE, move.host, move.board) === null) return false;
      const draft: VisitDraft = {
        host: move.host,
        fee: move.fee,
        ...(move.board !== undefined ? { board: move.board } : {}),
      };
      if (visitOffers(moves, draft).length === 0) return false;
      return visitComplete(moves, draft) === move;
    }

    case 'task':
      return taskReachable(position, move);

    // `collect` has no surface: it is a bonus-slot button beside Draw 1 under
    // the retired meeple-currency visit (`rules.turn.visitCurrency: 'meeple'`),
    // routed to `action-bar` the same as `bonusDraw` (`MOVE_ROUTES`) but never
    // offered under the shipped `data` this corpus is built with. Claimed here,
    // rather than left to fall through to `default`, so the exhaustive switch
    // still covers every move type - if this suite ever grows an arm position
    // under that currency, this case is where its click route belongs.
    case 'collect':
      return false;

    default:
      return move satisfies never;
  }
}

/**
 * ⏱️ THE BUILD OFFERS FOR ONE CARD, INDEXED ONCE PER POSITION.
 *
 * `buildCandidates` and `buildComplete` scan the WHOLE move list to find the
 * offers for one card, and `assembleBuild` calls one of them after every payment
 * click - so replaying a four-card payment was five full scans, once per build
 * move, in a list that since v31 runs to thousands. There is no hand limit any
 * more, so a mid-game hand of twenty makes `buildOptions` enumerate combinations
 * and the corpus positions carry move lists two orders of magnitude bigger than
 * the ones this file was written against. Measured: the three-seat sweep took
 * TEN MINUTES and still timed out.
 *
 * ⚠️ IT CHANGES NO ASSERTION. Both functions look only at build moves naming
 * `draft.card`, so handing them exactly that subset returns exactly the same
 * offers - the same objects, by identity, which is what the `=== move` check at
 * the end compares. What is removed is the rescanning, not the coverage.
 */
const BUILD_INDEX = new WeakMap<readonly Move[], Map<string, Move[]>>();

function buildMovesFor(moves: readonly Move[], card: string): Move[] {
  let byCard = BUILD_INDEX.get(moves);
  if (!byCard) {
    byCard = new Map();
    for (const move of moves) {
      const named =
        move.type === 'build'
          ? move.card
          : move.type === 'task' && move.answer.kind === 'build'
            ? move.answer.card
            : null;
      if (named === null) continue;
      const list = byCard.get(named);
      if (list) list.push(move);
      else byCard.set(named, [move]);
    }
    BUILD_INDEX.set(moves, byCard);
  }
  return byCard.get(card) ?? [];
}

/** Replay the build panel's clicks for a known target payment. */
function assembleBuild(
  moves: readonly Move[],
  card: string,
  payment: readonly string[],
  stacks: readonly string[],
): ReturnType<typeof buildComplete> {
  const offers = buildMovesFor(moves, card);
  let draft: BuildDraft = emptyBuildDraft(card);
  for (const paid of payment) {
    draft = withPayment(draft, paid);
    if (buildCandidates(offers, draft).length === 0) return null;
  }
  for (const paid of stacks) {
    draft = withStackPayment(draft, paid);
    if (buildCandidates(offers, draft).length === 0) return null;
  }
  return buildComplete(offers, draft);
}

/**
 * The build panel has to be OPENABLE, not merely completable.
 *
 * A build TASK (W7 Golden Field's harvest, the Dairy door) is the one task
 * with no in-place gesture: its answer names a card in the HAND, and a hand
 * click otherwise means "pick up". Assembling from a draft the test made itself
 * proved nothing about how a player gets that draft - which is how the panel
 * stayed dead behind a prompt that said "Build a card from your hand" while
 * this file was green. Both doors are checked: the action bar's Build family
 * must list the task's moves, and the card must be lit for the click that opens
 * the assembly.
 */
const ARMED_BUILD: Intent = { k: 'arm', type: 'build' };

/**
 * ⏱️ Memoised for the same reason the build index above is: this is called once
 * per build TASK and `liveTargets` under an armed Build asks `buildOffers` for
 * every card in the hand, so it is a hand-sized sweep of the move list every
 * time and the answer cannot change within one position.
 */
const PANEL_LIT = new WeakMap<readonly Move[], ReadonlySet<string> | null>();

function buildPanelOpens(position: Position, card: string): boolean {
  let lit = PANEL_LIT.get(position.moves);
  if (lit === undefined) {
    const bar = actionGroups(data, position.view, position.moves).find((g) => g.type === 'build');
    lit =
      !bar || bar.moves.length === 0
        ? null
        : liveTargets(position.view, position.moves, ARMED_BUILD).hand;
    PANEL_LIT.set(position.moves, lit);
  }
  return lit !== null && lit.has(card);
}

/**
 * `subsetAnswer` scans every move to resolve ONE answer, and this file calls it
 * once per move, so the pair is quadratic in the size of a keep/discard task.
 * That was free while hands stayed at the printed limit and went off a cliff on
 * 19/08/2026, when D7's wildcard ruling let a Dairy seat build without spending
 * hand cards: hands reached 17 against a limit of 7, one discard task offered
 * C(17,10) = 19,448 answers, and this test spent 192 SECONDS on a single
 * position against its 5s budget.
 *
 * ⚠️ THE INDEX IS A TEST-SPEED FIX AND NOTHING ELSE. It asserts exactly what the
 * scan asserted - the same answer object, found by the same card set - so the
 * coverage is unchanged, and `subsetAnswer` is still what the UI calls and is
 * still exercised through it below. The 19,448-answer task is NOT fixed by this
 * and is not meant to be: it is a real consequence of the ruling, it is written
 * up in `docs/turn-structure-arms-2026-08-19-v1.md`, and hiding it behind a
 * raised timeout is how it would have been missed.
 */
const SUBSET_INDEX = new WeakMap<readonly Move[], Map<string, Map<string, Move>>>();

function subsetKey(cards: readonly CardId[]): string {
  return [...cards].sort().join('|');
}

function subsetIndex(moves: readonly Move[], kind: 'keep' | 'discard'): Map<string, Move> {
  let byKind = SUBSET_INDEX.get(moves);
  if (!byKind) {
    byKind = new Map();
    SUBSET_INDEX.set(moves, byKind);
  }
  const cached = byKind.get(kind);
  if (cached) return cached;
  const index = new Map<string, Move>();
  for (const move of moves) {
    if (move.type !== 'task') continue;
    const answer = move.answer;
    if (answer.kind !== kind) continue;
    index.set(subsetKey(answer.cards), move);
  }
  byKind.set(kind, index);
  return index;
}

function taskReachable(position: Position, move: Move): boolean {
  if (move.type !== 'task') return false;
  const { moves } = position;
  const answer = move.answer;
  switch (answer.kind) {
    case 'deck':
      return clickDeck(moves, IDLE, answer.suit).includes(move);
    case 'building':
    case 'activate':
      return clickBuilding(moves, IDLE, answer.card).includes(move);
    case 'sow':
      return clickBuilding(moves, { k: 'hold', card: answer.card }, answer.onto).includes(move);
    case 'deliver':
      return clickTile(moves, IDLE, answer.tile).includes(move);
    case 'build':
      return (
        buildPanelOpens(position, answer.card) &&
        assembleBuild(moves, answer.card, answer.payment, answer.stacks ?? [])?.move === move
      );
    case 'keep':
      return subsetIndex(moves, 'keep').get(subsetKey(answer.cards)) === move;
    case 'discard':
      return subsetIndex(moves, 'discard').get(subsetKey(answer.cards)) === move;
    /*
     * ⭐ ROUTED 18/09/2026 (2.2.3), PROVEN HERE FOR GOOD. Off a deck top rather
     * than the hand, so there is no card to hold first: the building click
     * alone narrows to it (`clickBuilding` folds a `deckSow` answer into the
     * same `sows` bucket a held-card `sow` uses), and `clickDeck` finishes it
     * from the other end. Both halves have to agree, or the building could glow
     * for a move the deck click can never complete, or vice versa.
     */
    case 'deckSow':
      return (
        clickBuilding(moves, IDLE, answer.onto).includes(move) &&
        clickDeck(moves, IDLE, answer.suit).includes(move)
      );
    /*
     * ⭐ ROUTED 18/09/2026 (2.2.2), PROVEN HERE FOR GOOD. Naming the hand card
     * IS the whole answer - no destination to choose afterwards, unlike a build
     * or a sow - so picking the card up has to resolve it alone.
     */
    case 'handToBarn':
      return clickHandCard(moves, answer.card).includes(move);
    case 'skip':
    case 'card':
      // The prompt lists these explicitly; nothing to resolve.
      return moves.includes(move);
    /*
     * ⭐ ROUTED 18/09/2026 (2.2.5), PROVEN HERE FOR GOOD. Two shapes share the
     * kind (`UNROUTED_TASK_ANSWERS` is empty again as of the same date): the
     * Apiary retext's deck-paid Grow names a building and a DECK, no hand card,
     * so a building click alone narrows to it and a deck click finishes it -
     * exactly like `deckSow` above. A card-paid Grow (the Apiary Worker's plain
     * action, M7) names a building and the hand card that pays for it, so it
     * takes the same hold-then-click gesture `sow` does.
     */
    case 'grow':
      return answer.deckSuit !== undefined
        ? clickBuilding(moves, IDLE, answer.building).includes(move) &&
            clickDeck(moves, IDLE, answer.deckSuit).includes(move)
        : clickBuilding(
            moves,
            answer.payment !== null ? { k: 'hold', card: answer.payment } : IDLE,
            answer.building,
          ).includes(move);
    default:
      return answer satisfies never;
  }
}

const SEEDS = ['click-a', 'click-b'];

/**
 * ⏱️ THE SWEEPS ARE MINUTES, NOT SECONDS, AND THE CORPUS IS WHY.
 *
 * Three seeded games walked to 900 decisions each, at three seat counts, with a
 * scored bot choosing every move - and a mid-game hand makes `legalMoves`
 * enumerate build payments as C(hand, cost). Every one of those is then checked
 * for reachability, and each check is a scan of the same list - so the sweep is
 * quadratic in a number that grew
 * by an order of magnitude in v31. Measured on 02/09/2026: the three-seat table
 * ran TEN MINUTES before the build index and the single-pass resolvers, and
 * about three after.
 *
 * The budget is raised rather than the corpus cut, because what this file
 * catches is a move that is legal and cannot be clicked: it throws nothing, it
 * looks like nothing, and sampling would trade the whole point of the file for a
 * faster run.
 */
const SWEEP = 900_000;

/**
 * ⭐ THE TWO-PLAYER SHIPPED CORPUS (19/09/2026, 2.8.3). Built off `data` from
 * `session/table.ts` - the shipped rules, since the pin came down 18/09/2026 -
 * so every position in it is the two-board Notice Board visit, the token
 * island, Workers spent after the main action, and no balloons, Aerodrome or
 * Store coin: exactly what CLAUDE.md §0 calls the shipped default. It is the
 * one seat count where the two-board fix (S8, 11/09/2026) actually bites - at
 * 3p and 4p every farm has one board - so it is the corpus both the general
 * reachability sweep below AND the board-choosing test use.
 */
const TWO_PLAYER_SHIPPED = corpus(SEEDS, 2, ['wheat', 'orchard']);

describe('every legal move is reachable through the interface', () => {
  const tables: { name: string; positions: Position[] }[] = [
    { name: '2 seats', positions: TWO_PLAYER_SHIPPED },
    { name: '3 seats', positions: corpus(SEEDS, 3, ['wheat', 'vegetable', 'orchard']) },
    {
      name: '4 seats',
      positions: corpus(['click-c'], 4, ['wheat', 'vegetable', 'apiary', 'dairy']),
    },
  ];

  for (const { name, positions } of tables) {
    it(
      `at ${name}`,
      () => {
        expect(positions.length).toBeGreaterThan(200);
        const unreachable: string[] = [];
        for (const position of positions) {
          for (const move of position.moves) {
            if (!reachable(position, move)) {
              unreachable.push(
                `${move.type}${move.type === 'task' ? `/${move.answer.kind}` : ''}: ${JSON.stringify(move)}`,
              );
            }
          }
        }
        expect([...new Set(unreachable)].slice(0, 5)).toEqual([]);
      },
      SWEEP,
    );
  }

  /**
   * The index above replaced `subsetAnswer` in the hot loop for speed, so the
   * real UI function needs its own check or it would be uncovered here while
   * still being what the interface calls. Asserts the two AGREE, on every
   * keep/discard task the corpus actually contains, which is the property the
   * substitution relies on.
   */
  it('the subset index agrees with subsetAnswer, which is what the UI calls', () => {
    let checked = 0;
    for (const { positions } of tables) {
      for (const position of positions) {
        for (const kind of ['keep'] as const) {
          for (const [, move] of subsetIndex(position.moves, kind)) {
            if (move.type !== 'task') continue;
            const answer = move.answer;
            if (answer.kind !== kind) continue;
            expect(subsetAnswer(position.moves, kind, answer.cards)).toBe(move);
            checked += 1;
            if (checked > 400) return;
          }
        }
      }
    }
    expect(checked).toBeGreaterThan(0);
  });

  it('actually meets a build task, so its two doors are really being checked', () => {
    const tasks = tables.flatMap(({ positions }) =>
      positions.flatMap((p) =>
        p.moves.filter((m) => m.type === 'task' && m.answer.kind === 'build'),
      ),
    );
    expect(tasks.length).toBeGreaterThan(0);
  });

  it('exercises every move type the interface ROUTES, so the coverage means something', () => {
    const seen = new Set<MoveType>();
    for (const { positions } of tables) {
      for (const position of positions) {
        for (const move of position.moves) seen.add(move.type);
      }
    }
    /*
     * ⭐ THE `buy` / `market` EXEMPTION IS GONE, and its going is the good kind
     * of deletion. Both were rules SWITCHED OFF behind null knobs on 19/08/2026,
     * so the move types survived with nothing in any corpus able to offer one.
     * v31 deleted the currency, so both are gone from `MOVE_TYPES` entirely and
     * there is nothing left to exempt.
     *
     * ⚠️ FIVE TYPES ARE EXEMPT, AND EACH ONE IS A STATEMENT ABOUT THE GAME
     * RATHER THAN ABOUT THE INTERFACE. All five are routed (`MOVE_ROUTES`) and
     * all five are drawn wherever they are legal; what the corpus cannot do is
     * produce a position where one of them actually is.
     *
     *   pass       exists only for a turn with no legal main action at all,
     *              which a healthy game never reaches.
     *   endTurn    the engine SETTLES a turn the moment nothing is left to do
     *              (`settleTurn`), so a bot that always has something to do
     *              never declines anything. It went from rare to absent in v31,
     *              because a turn now carries a meeple phase and a bonus slot
     *              on top of the action and there is nearly always one of them
     *              live. The button is still drawn every turn, greyed when
     *              illegal, because it is the control a stuck HUMAN looks for -
     *              and a human can be stuck in ways a bot never is.
     *   cardMove   the only standing card move in the sheet is A Helping Hand's,
     *              and a corpus that never happens to build one of the five
     *              copies never offers it. `play.test.tsx` asserts the other
     *              half - wherever the move exists, the badge is on the card.
     *   bonusDraw  the free Draw 1 closed under `noticeBoardPower` on
     *              18/09/2026 (S5: the bonus slot holds one option, the visit,
     *              and a free solitaire Draw is what killed v31 at 67.6%). It
     *              is routed for the retired `'card'`/meeple currency arms
     *              this package's own tests still replay by name, but this
     *              corpus is built on `session/table.ts`'s shipped `data`,
     *              which never offers one.
     *   collect    exists only under `rules.turn.visitCurrency: 'meeple'`
     *              (the retired meeple loop), which no position in this
     *              corpus is built with.
     *
     * ⚠️ IF A BOT EVER STARTS DECLINING, A SECOND STANDING MOVE IS PRINTED, OR
     * THE SHIPPED DEFAULT EVER REOPENS THE FREE DRAW, DELETE THAT EXEMPTION. An
     * exemption is what would otherwise hide a genuinely unreachable rule,
     * which is the exact failure this file exists to catch.
     */
    const UNREACHED: readonly MoveType[] = ['pass', 'endTurn', 'cardMove', 'bonusDraw', 'collect'];
    const missing = MOVE_TYPES.filter((t) => !seen.has(t) && !UNREACHED.includes(t));
    expect(missing).toEqual([]);
  });

  /**
   * The other half of `UNROUTED_TASK_ANSWERS`: the kinds it names must be
   * genuinely absent from the game this package plays. The day the corpus can
   * produce one, the admission is wrong and has to be re-argued rather than
   * quietly relied on.
   */
  it('never meets a task answer kind it has admitted it cannot resolve', () => {
    const met = new Set<string>();
    for (const { positions } of tables) {
      for (const position of positions) {
        for (const move of position.moves) {
          if (move.type === 'task') met.add(move.answer.kind);
        }
      }
    }
    expect(UNROUTED_TASK_ANSWERS.filter((kind) => met.has(kind))).toEqual([]);
  });
});

/**
 * The drift test: the engine grows a move type and the interface does not. It
 * must not be weakened into "the routes are a subset" - the routes and the
 * engine's move types must be the same set, so a deleted move type fails too.
 */
describe('the route table cannot drift from the engine', () => {
  it('routes every move type the engine can offer, and nothing else', () => {
    const routed = Object.keys(MOVE_ROUTES) as MoveType[];
    expect([...routed].sort()).toEqual([...MOVE_TYPES].sort());
  });
});

describe('what glows', () => {
  const positions = corpus(['glow'], 3, ['wheat', 'vegetable', 'orchard']);

  it('lights nothing when there is nothing to do', () => {
    const first = positions[0] as Position;
    const live = liveTargets(first.view, [], IDLE);
    expect(live.buildings.size + live.hosts.size + live.tiles.size + live.hand.size).toBe(0);
  });

  it('never lights a target whose click resolves to nothing', () => {
    for (const { view, moves } of positions) {
      const live = liveTargets(view, moves, IDLE);
      for (const card of live.buildings) {
        expect(clickBuilding(moves, IDLE, card).length).toBeGreaterThan(0);
      }
      for (const tile of live.tiles) expect(clickTile(moves, IDLE, tile).length).toBeGreaterThan(0);
      for (const seat of live.hosts) expect(clickHost(view, moves, IDLE, seat)).not.toBeNull();
      for (const colour of live.meeples) {
        expect(clickMeeple(moves, colour).length).toBeGreaterThan(0);
      }
    }
  });

  /**
   * ⭐ A VISIT NEVER LIGHTS YOUR OWN BOARD (19/09/2026, was the opposite claim
   * under v31). Self-visiting is banned under the shipped rules (Dean,
   * 11/09/2026: it measured 44.4% of visits and the neighbour hook had no
   * subject), so an armed `visit` family must light every rival's door and
   * never your own - the `self` flag `Intent.arm` still carries exists only
   * for the retired pre-ban `'card'` control (`FAMILIES`'s `visit-self` entry
   * in `moveText.ts`), and passing it `true` here must light nothing at all
   * under the shipped `data` this corpus is built with.
   */
  it('never lights your own board as a visit target, under the shipped rules', () => {
    let checkedOther = 0;
    for (const { view, moves } of positions) {
      const armed = liveTargets(view, moves, { k: 'arm', type: 'visit' });
      const selfArmed = liveTargets(view, moves, { k: 'arm', type: 'visit', self: true });
      expect(selfArmed.hosts.size).toBe(0);
      for (const seat of armed.hosts) {
        expect(seat).not.toBe(view.seat);
        checkedOther += 1;
      }
    }
    // Must really occur in the corpus, or the assertion is vacuous: a visit
    // that never appears would pass this test and be unplayable.
    expect(checkedOther).toBeGreaterThan(0);
  });

  it('narrows the hand to the payment while a build is being assembled', () => {
    const withBuild = positions.find((p) => p.moves.some((m) => m.type === 'build'));
    expect(withBuild).toBeDefined();
    const build = (withBuild as Position).moves.find((m) => m.type === 'build') as Extract<
      Move,
      { type: 'build' }
    >;
    const intent: Intent = { k: 'build', draft: emptyBuildDraft(build.card) };
    const live = liveTargets((withBuild as Position).view, (withBuild as Position).moves, intent);
    // The card being built never pays for itself, and nothing else on the table
    // is a target while a payment is open.
    expect(live.hand.has(build.card)).toBe(false);
    expect(live.buildings.size).toBe(0);
    expect(live.tiles.size).toBe(0);
  });

  it('lights only the host being visited once a visit is open', () => {
    const withVisit = positions.find((p) => p.moves.some((m) => m.type === 'visit'));
    expect(withVisit).toBeDefined();
    const visit = (withVisit as Position).moves.find((m) => m.type === 'visit') as Extract<
      Move,
      { type: 'visit' }
    >;
    const live = liveTargets((withVisit as Position).view, (withVisit as Position).moves, {
      k: 'visit',
      host: visit.host,
      fee: null,
    });
    expect([...live.hosts]).toEqual([visit.host]);
  });
});

/**
 * ⭐ THE VISIT CHOOSES A BOARD (18/09/2026, 2.2.1 / 2.8.3). At two players a
 * host lays out two Notice Boards (the two-board fix, S8) with two different
 * printed powers, so a draft that never named one could still narrow to more
 * than one surviving move - the exact bug `reachable()`'s `case 'visit'` had
 * before it threaded `move.board` through `clickHost` and the draft: it built
 * `{ host, fee }` only, so a two-board host's SECOND board could survive the
 * narrowing purely by which move happened to sort first, and this file would
 * still have gone green.
 */
describe('the visit chooses a board, on the two-player shipped corpus', () => {
  it('found a host offering more than one Notice Board', () => {
    const twoBoardHost = TWO_PLAYER_SHIPPED.some(({ moves }) =>
      [...new Set(moves.filter((m) => m.type === 'visit').map((m) => m.host))].some(
        (host) => visitBoards(moves, host).length > 1,
      ),
    );
    expect(twoBoardHost).toBe(true);
  });

  it('every board a two-board host offers narrows to its own move, not the other one', () => {
    let checked = 0;
    for (const { view, moves } of TWO_PLAYER_SHIPPED) {
      const hosts = new Set(moves.filter((m) => m.type === 'visit').map((m) => m.host));
      for (const host of hosts) {
        const boards = visitBoards(moves, host);
        if (boards.length < 2) continue;
        for (const board of boards) {
          const opened = clickHost(view, moves, IDLE, host, board);
          expect(opened).not.toBeNull();
          const draft: VisitDraft = { host, board, fee: null };
          for (const offer of visitOffers(moves, draft)) {
            // Every surviving offer really is on THIS board, never the host's
            // other one - the property `move.board` being threaded through is
            // what guarantees.
            expect(offer.board).toBe(board);
          }
          checked += 1;
        }
      }
    }
    // Must really occur, or the assertion is vacuous.
    expect(checked).toBeGreaterThan(0);
  });

  it('the fully-specified draft (host, board, fee) resolves to one move, never the other board', () => {
    let checked = 0;
    for (const position of TWO_PLAYER_SHIPPED) {
      for (const move of position.moves) {
        if (move.type !== 'visit' || move.board === undefined) continue;
        const boards = visitBoards(position.moves, move.host);
        if (boards.length < 2) continue;
        expect(reachable(position, move)).toBe(true);
        checked += 1;
      }
    }
    expect(checked).toBeGreaterThan(0);
  });
});
