/**
 * @gp/data - card, island, worker, aerodrome and rules data, and the tuning
 * overlay the simulator varies it through.
 *
 * Platform-free, like the engine: the JSON is imported, never read from disk, so
 * the browser and Node get the same bytes with no loader to keep in sync.
 *
 * The split into five files follows PROVENANCE, not convenience:
 *
 *   cards.json      generated by tools/extract_cards.py from the sheet. Never
 *                   hand-edited: an edit here is overwritten by the next extract.
 *   island.json     authored, from the sheet's map tab plus the rulebook tables.
 *   workers.json    authored. Deliberately in no sheet - the sheet's components
 *                   tab is stale material from an older edition.
 *   aerodrome.json  authored, from the printed art and the rulebook.
 *   rules.json      authored. The numbers that belong to no single card.
 *
 * Every file declares `meta.kind`, so "may I edit this by hand" is answerable
 * from the file itself.
 */

import cardsJson from '../data/cards.json' with { type: 'json' };
import islandJson from '../data/island.json' with { type: 'json' };
import workersJson from '../data/workers.json' with { type: 'json' };
import aerodromeJson from '../data/aerodrome.json' with { type: 'json' };
import rulesJson from '../data/rules.json' with { type: 'json' };

import { deepFreeze } from './paths.js';
import { applyOverlay } from './overlay.js';
import type { Overlay } from './overlay.js';
import type {
  AerodromeFile,
  CardsFile,
  GameData,
  IslandFile,
  RulesFile,
  WorkersFile,
} from './types.js';

export * from './types.js';
export { flatten, getPath, setPath, cloneData, deepFreeze } from './paths.js';
export type { Leaf } from './paths.js';
export { KNOB_TEMPLATES, listKnobs, deadTemplates } from './knobs.js';
export type { Knob, KnobTemplate, KnobType } from './knobs.js';
export {
  OVERLAY_SCHEMA_VERSION,
  OverlayError,
  DEFAULT_MAX_SWEEP_CELLS,
  validateOverlay,
  applyOverlay,
  expandSweep,
} from './overlay.js';
export type { Overlay, SweepAxis, SweepCell, SweepFile } from './overlay.js';

/**
 * ⛔ `serviceCardId` and `withServices` are GONE (change 6, 20/08/2026), and so
 * is the last of the vocabulary around them (v31, 02/09/2026).
 *
 * They synthesised five SERVICE starter cards out of `workers.json` - a fourth
 * starter per seat that a rival could place a card on to buy the suit's action.
 * Change 6 merged that door into the NOTICE BOARD, which is a real card in the
 * extract and always was, so there is nothing left to synthesise:
 * `data.cards.catalogue` is exactly the 105 rows of the sheet.
 *
 * Where the pieces went:
 *
 * - the door's THRESHOLD is `rules.economy.noticeBoardThreshold`, an override of
 *   the Notice Board's own printed value. `workers.serviceThreshold` is deleted:
 *   one number in two files is exactly how the old 5-versus-2 drift happened,
 *   and the v31 sheet prints 2, so override and print now agree.
 * - `workers.roster` SURVIVES and is now read by TWO consumers, not one: a suit's
 *   Notice Board grants its action to a visitor, and a MEEPLE of that colour
 *   performs the same action free when spent. It stopped describing a card; it
 *   never stopped describing behaviour.
 * - `ownerActivationCost` and `visitWage` are deleted with the currency. In v31
 *   the owner places a card on their own board exactly as a rival does.
 */

/**
 * The committed numbers, with no overlay applied. Frozen: a caller that mutates
 * shared data would turn a balance run into a mystery, so the freeze converts
 * that into an exception at the point of the write.
 */
export const BASE_GAME_DATA: GameData = deepFreeze({
  cards: cardsJson as unknown as CardsFile,
  island: islandJson as unknown as IslandFile,
  workers: workersJson as unknown as WorkersFile,
  aerodrome: aerodromeJson as unknown as AerodromeFile,
  rules: rulesJson as unknown as RulesFile,
});

/**
 * The data a game or a simulation run reads.
 *
 * With no overlay this is `BASE_GAME_DATA` itself. With one, it is a fresh tree
 * with the overlay's leaves replaced, validated first: an unknown path, a path
 * the current extract no longer has, a type mismatch or a schema mismatch all
 * throw rather than silently doing nothing.
 */
export function loadGameData(overlay?: Overlay): GameData {
  if (!overlay) return BASE_GAME_DATA;
  return deepFreeze(applyOverlay(BASE_GAME_DATA, overlay));
}

/**
 * The DOOR a suit owns: the action its Notice Board grants, which is also the
 * action a meeple of that colour performs. Undefined if that suit has none,
 * which cannot happen in the shipped data and is asserted in `data.test.ts`.
 */
export function doorForSuit(data: GameData, suit: string) {
  return data.workers.roster.find((w) => w.linkedSuit === suit);
}

/** @deprecated The Services are gone (v31). Use `doorForSuit`. */
export const serviceForSuit = doorForSuit;

/**
 * The action a meeple of this colour performs when spent. Identical to the
 * suit's door by rule, and routed through one function so that stays true: a
 * meeple of a suit NOT at the table still works, so this must never be gated on
 * whether anybody owns that Notice Board.
 */
export function meepleAction(data: GameData, colour: string) {
  return doorForSuit(data, colour)?.action;
}

/**
 * Meeples dealt onto the island at setup: one per delivery space, so tiles in
 * play times deliveries per tile times `perDeliverySpace`. Derived rather than
 * stored, because the bag has to be checked against it - at 4 seats this is 24
 * against a pool of 25.
 */
export function meeplesDealt(data: GameData, seats: number): number {
  const rows = data.island.slotsBySeats[String(seats)];
  if (!rows) return 0;
  const tiles = Object.values(rows).reduce((n, count) => n + count, 0);
  return tiles * meeplesPerTile(data);
}

/**
 * Is the MEEPLE-LOOP ARM on? One predicate, so that "which game are we playing"
 * is asked in exactly one spelling across the engine, the bots and the sim.
 *
 * Everything it gates: the visit's currency, the Notice Board being a building
 * at all, the bonus slot's second option, the turn-start meeple spend, the
 * supply cap and which island spaces carry a meeple.
 *
 * ⭐ IT DEFAULTS TRUE SINCE 04/09/2026, WHEN DEAN RULED THE MEEPLE LOOP IN. It
 * was written as an arm predicate with `'card'` as the shipped game; the two
 * have swapped, so `'card'` is now the CONTROL at
 * `overlays/v31-card-visit.overlay.json` and a `false` here must reach exactly
 * the code that ran on 03/09/2026. That branch is not dead code and must not be
 * tidied away: it is the baseline every future delta is read against, and the
 * only thing exercising it at scale is that overlay.
 */
export function isMeepleCurrency(data: GameData): boolean {
  return data.rules.turn.visitCurrency === 'meeple';
}

/**
 * Is R15 live - a meeple spendable as a card of its colour? See
 * `rules.turn.meepleAsCard`.
 *
 * ⭐ DEFAULTS FALSE. The knob is meaningless outside the meeple loop, but this
 * does not gate on `isMeepleCurrency` itself - the data can never set
 * `meepleAsCard` true while `visitCurrency` is `'card'` in practice, because
 * only handoff-v2 overlays touch it and they all set `visitCurrency: 'meeple'`
 * in the same breath. Callers that already know they are in the meeple arm may
 * read this directly; callers that do not should check `isMeepleCurrency`
 * first.
 */
export function isMeepleAsCard(data: GameData): boolean {
  return data.rules.turn.meepleAsCard;
}

/**
 * The amended R6 slot price, or null for the v1 block. See
 * `rules.turn.slotToll`.
 *
 * null: a slot holding any meeple is BLOCKED and refuses that colour outright.
 * A number n: nothing is ever refused, and visiting a slot already holding k
 * meeples costs n * k extra meeples of any colours - the toll - on top of the
 * acting meeple, boxed rather than handed to the host.
 */
export function slotTollOf(data: GameData): number | null {
  return data.rules.turn.slotToll;
}

/**
 * ⭐ R17: does a meeple spent as a CARD land on a neighbour's board rather
 * than in the box? Only ever true when `meepleAsCard` is on as well - there is
 * nothing to place when a meeple cannot pay for anything.
 */
export function meepleAsCardGoesToBoard(data: GameData): boolean {
  return data.rules.turn.meepleAsCard && data.rules.turn.meepleAsCardGoesTo === 'board';
}

/** The FLAT toll for placing a paid meeple onto an occupied slot (R17). */
export function paymentSlotTollOf(data: GameData): number {
  return data.rules.turn.paymentSlotToll;
}

/**
 * How many meeples one tile is seeded with at setup.
 *
 * Under the shipped `'meeple'` it is the length of `island.meeples.seededSpaces`
 * - `[1]`, the 3 VP second delivery - because the rule names WHICH spaces carry
 * one rather than how many each carries, and which is the whole of the design:
 * being first to a tile is 6 VP flat, being second is 3 VP plus a stored action.
 * Under the `'card'` control it is every delivery space times
 * `perDeliverySpace`, exactly as v31 dealt them, which is twice as deep a draw
 * from the same bag.
 */
export function meeplesPerTile(data: GameData): number {
  if (isMeepleCurrency(data)) {
    return data.island.meeples.seededSpaces.filter((i) => i >= 0 && i < deliveriesPerTile(data))
      .length;
  }
  return deliveriesPerTile(data) * data.island.meeples.perDeliverySpace;
}

/**
 * Which entry of a tile's `meeples` array belongs to delivery space `space`, or
 * -1 for a space that carries no meeple.
 *
 * ⭐ THE ARRAY IS DENSE AND THE SPACES ARE NOT, which is the whole reason this
 * function exists. Under `'card'` every space has a meeple and the mapping is
 * the identity, so nothing changes for the control. Under `'meeple'` only the
 * seeded spaces do, and a tile holding one meeple for space 1 stores it at index
 * 0 - a sparse array would not survive a JSON round-trip through a capture, and
 * a nullable one would push the hole into every reader.
 */
export function meepleIndexForSpace(data: GameData, space: number): number {
  if (!isMeepleCurrency(data)) return space;
  return data.island.meeples.seededSpaces.indexOf(space);
}

/** Cards actually in the game: the enable flag applied. */
export function activeCards(data: GameData = BASE_GAME_DATA) {
  return data.cards.catalogue.filter((card) => card.enabled);
}

/**
 * Total barn cards a tile costs: one demand per crate, each paid in
 * `cardsPerCrate` cards. Derived rather than stored, so a knob on either factor
 * moves the real cost instead of half of it. No level argument since the flat
 * island - every tile costs the same.
 */
export function deliveryCost(data: GameData): number {
  const { crates, cardsPerCrate } = data.island.tileRule;
  return crates * cardsPerCrate;
}

/** How many deliveries one tile accepts. The VP schedule's length IS the rule. */
export function deliveriesPerTile(data: GameData): number {
  return data.island.vpByDeliveryOrder.length;
}

/**
 * VP the next delivery to a tile with `already` receipts on it would take. 0
 * past the end of the schedule, which is also the tile being full - callers
 * check capacity, this never invents a value for an illegal delivery.
 */
export function deliveryVp(data: GameData, already: number): number {
  return data.island.vpByDeliveryOrder[already] ?? 0;
}
