/**
 * @gp/data - card, island, worker, aerodrome and rules data, and the tuning
 * overlay the simulator varies it through.
 *
 * Platform-free, like the engine: the JSON is imported, never read from disk, so
 * the browser and Node get the same bytes with no loader to keep in sync.
 *
 * The split into five files follows PROVENANCE, not convenience:
 *
 *   cards.json      generated by tools/extract_cards.py from the sheet. Never
 *                   hand-edited: an edit here is overwritten by the next extract.
 *   island.json     authored, from the sheet's map tab plus the rulebook tables.
 *   workers.json    authored. Deliberately in no sheet - the sheet's components
 *                   tab is stale material from an older edition.
 *   aerodrome.json  authored, from the printed art and the rulebook.
 *   rules.json      authored. The numbers that belong to no single card.
 *
 * Every file declares `meta.kind`, so "may I edit this by hand" is answerable
 * from the file itself.
 */

import cardsJson from '../data/cards.json' with { type: 'json' };
import islandJson from '../data/island.json' with { type: 'json' };
import workersJson from '../data/workers.json' with { type: 'json' };
import aerodromeJson from '../data/aerodrome.json' with { type: 'json' };
import rulesJson from '../data/rules.json' with { type: 'json' };

import { deepFreeze } from './paths.js';
import { applyOverlay } from './overlay.js';
import type { Overlay } from './overlay.js';
import type {
  AerodromeFile,
  CardsFile,
  DoorAction,
  GameData,
  IslandFile,
  MeepleSpendTiming,
  RulesFile,
  WorkersFile,
} from './types.js';

export * from './types.js';
export { flatten, getPath, setPath, cloneData, deepFreeze } from './paths.js';
export type { Leaf } from './paths.js';
export { KNOB_TEMPLATES, listKnobs, deadTemplates } from './knobs.js';
export type { Knob, KnobTemplate, KnobType } from './knobs.js';
export {
  OVERLAY_SCHEMA_VERSION,
  OverlayError,
  DEFAULT_MAX_SWEEP_CELLS,
  validateOverlay,
  applyOverlay,
  expandSweep,
} from './overlay.js';
export type { Overlay, SweepAxis, SweepCell, SweepFile } from './overlay.js';

/**
 * ⛔ `serviceCardId` and `withServices` are GONE (change 6, 20/08/2026), and so
 * is the last of the vocabulary around them (v31, 02/09/2026).
 *
 * They synthesised five SERVICE starter cards out of `workers.json` - a fourth
 * starter per seat that a rival could place a card on to buy the suit's action.
 * Change 6 merged that door into the NOTICE BOARD, which is a real card in the
 * extract and always was, so there is nothing left to synthesise:
 * `data.cards.catalogue` is exactly the 105 rows of the sheet.
 *
 * Where the pieces went:
 *
 * - the door's THRESHOLD is `rules.economy.noticeBoardThreshold`, an override of
 *   the Notice Board's own printed value. `workers.serviceThreshold` is deleted:
 *   one number in two files is exactly how the old 5-versus-2 drift happened.
 *   ⚠️ OVERRIDE AND PRINT AGREED FROM v31 UNTIL 10/09/2026 AND DO NOT NOW: the
 *   override is 3 (S8's `3+`) and the sheet still prints 2 until
 *   `Isle-of-Farms-v36.xlsm`. The face is what has to catch up, and the v31
 *   control pins 2 so its own game is unchanged.
 * - `workers.roster` SURVIVES and is now read by TWO consumers, not one: a suit's
 *   Notice Board grants its action to a visitor, and a MEEPLE of that colour
 *   performs the same action free when spent. It stopped describing a card; it
 *   never stopped describing behaviour.
 * - `ownerActivationCost` and `visitWage` are deleted with the currency. In v31
 *   the owner places a card on their own board exactly as a rival does.
 */

/**
 * The committed numbers, with no overlay applied. Frozen: a caller that mutates
 * shared data would turn a balance run into a mystery, so the freeze converts
 * that into an exception at the point of the write.
 */
export const BASE_GAME_DATA: GameData = deepFreeze({
  cards: cardsJson as unknown as CardsFile,
  island: islandJson as unknown as IslandFile,
  workers: workersJson as unknown as WorkersFile,
  aerodrome: aerodromeJson as unknown as AerodromeFile,
  rules: rulesJson as unknown as RulesFile,
});

/**
 * The data a game or a simulation run reads.
 *
 * With no overlay this is `BASE_GAME_DATA` itself. With one, it is a fresh tree
 * with the overlay's leaves replaced, validated first: an unknown path, a path
 * the current extract no longer has, a type mismatch or a schema mismatch all
 * throw rather than silently doing nothing.
 */
export function loadGameData(overlay?: Overlay): GameData {
  if (!overlay) return BASE_GAME_DATA;
  return deepFreeze(applyOverlay(BASE_GAME_DATA, overlay));
}

/**
 * The DOOR a suit owns: the action its Notice Board grants, which is also the
 * action a meeple of that colour performs. Undefined if that suit has none,
 * which cannot happen in the shipped data and is asserted in `data.test.ts`.
 */
export function doorForSuit(data: GameData, suit: string) {
  return data.workers.roster.find((w) => w.linkedSuit === suit);
}

/** @deprecated The Services are gone (v31). Use `doorForSuit`. */
export const serviceForSuit = doorForSuit;

/**
 * The action a meeple of this colour performs when spent. Identical to the
 * suit's door by rule, and routed through one function so that stays true: a
 * meeple of a suit NOT at the table still works, so this must never be gated on
 * whether anybody owns that Notice Board.
 */
export function meepleAction(data: GameData, colour: string) {
  return doorForSuit(data, colour)?.action;
}

/**
 * ⭐ WHAT A SUIT'S DOOR BUYS IN THE GAME CURRENTLY LOADED, which is not always
 * `door.action` any more: under the commons the Apiary board buys a GROW
 * (`workers.roster.sow.actionUnderCommons`, Dean 09/09/2026, C3) where the v31
 * door and the meeple both bought a SOW.
 *
 * One function, so "which action is this door" is answered in one spelling
 * across the engine, the bots and the sim, exactly as `meepleAction` did for the
 * meeple. Anything that DISPATCHES on a door's action must come through here;
 * anything that enumerates the five suit doors as a set may keep reading
 * `door.action`, because the set is the same five boards either way.
 *
 * Undefined if that suit has no door, which cannot happen in the shipped data.
 */
export function doorActionForSuit(data: GameData, suit: string): DoorAction | undefined {
  const door = doorForSuit(data, suit);
  if (!door) return undefined;
  return (isCommons(data) ? door.actionUnderCommons : undefined) ?? door.action;
}

/**
 * Meeples dealt onto the island at setup: one per delivery space, so tiles in
 * play times deliveries per tile times `perDeliverySpace`. Derived rather than
 * stored, because the bag has to be checked against it - at 4 seats this is 24
 * against a pool of 25.
 */
export function meeplesDealt(data: GameData, seats: number): number {
  const rows = data.island.slotsBySeats[String(seats)];
  if (!rows) return 0;
  const tiles = Object.values(rows).reduce((n, count) => n + count, 0);
  return tiles * meeplesPerTile(data);
}

/**
 * Is the MEEPLE-LOOP ARM on? One predicate, so that "which game are we playing"
 * is asked in exactly one spelling across the engine, the bots and the sim.
 *
 * Everything it gates: the visit's currency, the Notice Board being a building
 * at all, the bonus slot's second option, the turn-start meeple spend, the
 * supply cap and which island spaces carry a meeple.
 *
 * ⭐ IT DEFAULTS FALSE AGAIN SINCE 09/09/2026, WHEN DEAN RULED THE COMMONS IN.
 * It was written as an arm predicate with `'card'` as the shipped game, was the
 * shipped game itself from 04/09 to 09/09/2026, and is now one of TWO controls -
 * `overlays/meeple-loop-v1.overlay.json` for the v1 loop and
 * `overlays/meeple-economy-v1.overlay.json` for the reference-v14 game.
 *
 * ⛔ NEITHER THIS BRANCH NOR THE `'card'` ONE IS DEAD CODE, and neither may be
 * tidied away: they are the baselines every future delta is read against, and
 * the only things exercising them at scale are those overlays. ⚠️ AND A FALSE
 * HERE NO LONGER MEANS "the v31 game" - it means "not the meeple game", which
 * under the shipped default is the commons. Ask `isCommons` when the question is
 * which game, and this only when the question is meeples.
 */
export function isMeepleCurrency(data: GameData): boolean {
  return data.rules.turn.visitCurrency === 'meeple';
}

/**
 * Is the COMMONS live - the bonus slot of 09/09/2026? Under `'commons'` the five
 * Notice Boards sit ownerless in the centre of the table, the bonus (taken
 * FIRST) is to play any one card from hand onto one of them and take that
 * board's action, Harvest may take any non-empty central pile into the
 * harvester's barn, and there are no meeples anywhere. The `'card'` (v31) and
 * `'meeple'` (04-05/09/2026) branches are the controls and must not be tidied
 * away. See `docs/commons-handoff-2026-09-09-v1.md`.
 */
export function isCommons(data: GameData): boolean {
  return data.rules.turn.visitCurrency === 'commons';
}

/**
 * Is the NOTICE BOARD VISIT live - the arm of 10/09/2026
 * (`docs/notice-board-visit-handoff-2026-09-10-v2.md`, S1-S16)? Under it the
 * centre is deleted, the five Notice Board cards go home to their owners' farms
 * and are BUILDINGS again, and the bonus (still taken FIRST) is to play one card
 * from your hand onto ANY player's Notice Board, your own included, and take
 * that board's PRINTED POWER. The card rests on the host's board until the host
 * harvests it into their barn, which is the host's whole payment.
 *
 * ⛔ IT IS A FOURTH CURRENCY AND NOT A REPOINTING OF `'card'`. The v31 control
 * carries three passengers this design does not want - a blocking board at 2,
 * the standalone free Draw 1, and the turn-start meeple spend - and one of the
 * three named controls may never move under an arm it is read against.
 *
 * One predicate, in one spelling, exactly as `isCommons` and `isMeepleCurrency`
 * are: everything gated on which game this is asks one of the three and never
 * compares the raw string.
 */
export function isNoticeBoardPower(data: GameData): boolean {
  return data.rules.turn.visitCurrency === 'noticeBoardPower';
}

/**
 * Does a Notice Board CLOG at its threshold, or is the threshold only a minimum
 * to harvest at (S8, Dean 10/09/2026)?
 *
 * `false` is the shipped value and the `3+` rule: the board is harvestable at or
 * above `rules.economy.noticeBoardThreshold` and still accepts cards for ever.
 * `true` is the paired control that makes it an ordinary clogging building.
 *
 * ⛔ IT IS THE SEAM WHERE `isFull` AND `canTakeCard` STOP BEING THE SAME
 * QUESTION, which they have been everywhere in this codebase until now. A board
 * at five cards is harvestable AND still takes another; a caller that asks
 * "is it full" when it means "may I place here" will be wrong under the shipped
 * value and right under the control, which is the worst way round.
 *
 * ⚠️ Read only under `isNoticeBoardPower`: no other game has an owned Notice
 * Board with a threshold on it.
 */
export function noticeBoardBlocks(data: GameData): boolean {
  return data.rules.economy.noticeBoardBlocks;
}

/**
 * Do the Notice Boards of the suits NOBODY IS FARMING stand ownerless in the
 * CENTRE of the table (Dean, ruled 11/09/2026)?
 *
 * `false` is the shipped value: every Notice Board belongs to a player, so a
 * suit nobody has taken has no board on the table at all. `true` puts the
 * unclaimed ones in the middle with a face-up public pile each, visitable by
 * anybody.
 *
 * ⭐ IT IS RULED TOGETHER WITH A BAN ON SELF-VISITING, and the pair is
 * arithmetic rather than taste: five boards exist and you may never visit your
 * own, so EVERY SEAT FACES EXACTLY FOUR TARGETS AT EVERY PLAYER COUNT - four
 * central at one seat, three at two, two at three, one at four. It also restores
 * the standing ruling that all five actions exist in every game, which the built
 * design silently broke: at two players only two Notice Boards are in play.
 *
 * ⚠️ A CENTRAL BOARD REUSES THE COMMONS AND IS NOT A THIRD SHAPE. A play
 * onto a rival's board is the `visit` move; a play onto a central board is the
 * existing `commons` move, and a central pile is rationed by the commons knobs
 * (`commonsThreshold`, `commonsHarvestMin`, `commonsHarvestTake`) under
 * `rules.turn.commonsTake` `'harvest'`, which the two overlays pin by name.
 *
 * ⛔ READ ONLY UNDER `isNoticeBoardPower`, exactly as `noticeBoardBlocks` is:
 * no other game in this codebase has an owned Notice Board to leave unclaimed.
 * Under `'commons'` all five are in the centre already and none of them is
 * owned, which is a different rule that reads the same way round.
 */
export function unclaimedBoardsToCentre(data: GameData): boolean {
  return data.rules.economy.unclaimedBoardsToCentre;
}

/**
 * How many Notice Boards each player lays out at this seat count (Dean's
 * two-board fix, ruled 11/09/2026). One accessor, so "how many boards has a
 * seat got" is asked in exactly one spelling across the engine, the bots and the
 * sim, exactly as `meeplesDealt` reads `island.slotsBySeats`.
 *
 * Shipped at 1 at every seat count, which is the game as built. The arm sets 2
 * at two seats only: a player's own suit's board, plus one more drawn AT RANDOM
 * from the suits nobody is farming, with the fifth board unused. At three and
 * four seats the arm is its own control, so those columns must reproduce
 * `overlays/notice-board-visit-no-self-v1.overlay.json` on identical seeds and
 * any difference there is a leak rather than a finding.
 *
 * ⭐ EVERY BOARD IT ADDS BELONGS TO A PERSON, which is the difference between
 * this and `unclaimedBoardsToCentre`: targets go 2 / 2 / 3 by seat count and
 * every one of them pays its owner, so the hook is not diluted.
 *
 * ⛔ READ ONLY UNDER `isNoticeBoardPower` with `rules.turn.selfVisitAllowed`
 * false: no other game in this codebase has an owned Notice Board to duplicate.
 *
 * ⚠️ THE CEILING IS ARITHMETIC AND THIS FUNCTION DOES NOT ENFORCE IT. The suits
 * nobody is farming number `5 - seats`, so `n` boards each is realisable only
 * where `seats * (n - 1) <= 5 - seats`: 2 at two seats, 1 at three and four. An
 * overlay may ask for more, because the knob is a free map; what to do about an
 * infeasible value is an ENGINE ruling and it has not been made.
 *
 * Falls back to 1 for a seat count the map does not name, which is the shipped
 * rule rather than a guess.
 */
export function noticeBoardsPerSeat(data: GameData, seats: number): number {
  return data.rules.economy.noticeBoardsBySeats[String(seats)] ?? 1;
}

/**
 * How many cards the OWNER of a Notice Board draws when somebody else visits it
 * (S17, Dean, ruled 11/09/2026). One accessor, so "what does a host get" is asked
 * in exactly one spelling across the engine, the bots and the sim.
 *
 * Shipped at 0, which is the game as built and the rule as S7 wrote it: the card
 * the visitor pays rests on the board until its owner harvests it, and that is
 * the payment and there is no other. 1 is
 * `overlays/notice-board-visit-host-draw-v1.overlay.json`, where the host is
 * ALSO paid instantly, in a card off a deck.
 *
 * ⭐ ITS PROVENANCE IS A TABLE RATHER THAN A SIMULATION. Dean played
 * `overlays/notice-board-visit-two-boards-v1.overlay.json` at a two-player table
 * on 11/09/2026, house-ruled this in mid-session, and reported that it *"led to
 * a lot of extra cards in play, which relieved the tightness of the game in a
 * useful way"*. See `rules.turn.hostDrawOnVisit` for the amendment to S7 and for
 * the lens argument.
 *
 * ⛔ READ ONLY UNDER `isNoticeBoardPower`, exactly as `noticeBoardBlocks` and
 * `noticeBoardsPerSeat` are: no other game in this codebase has a host at all.
 * Under the commons a board belongs to nobody, so there is nobody to pay.
 *
 * ⛔ AND A SELF-VISIT MUST NEVER PAY IT. This function says how much a host
 * draws; it is the CALLER's job never to ask it about a visitor visiting
 * themselves. `turn.selfVisitAllowed` is false on the arm that matters, so the
 * case has no subject there, but a card drawn for visiting yourself is a pure
 * faucet paid by nobody and it must not be reachable.
 *
 * ⚠️ EVERY VISIT PAID THIS WAY ADDS A CARD TO THE GAME - about 14.4 visits
 * received per player per game at two seats under the control arm - and the
 * simulator cannot measure the effect Dean liked, because the engine's hand
 * limit of 7 is an instrument bound (C7) and the table plays with none.
 */
export function hostDrawOnVisit(data: GameData): number {
  return data.rules.turn.hostDrawOnVisit;
}

/**
 * ⭐ IS THE HOST-DRAW CAP ON - is a host paid AT MOST ONCE between their own
 * turns, however many neighbours visit them in the meantime?
 * (`rules.turn.hostDrawCapPerRound`, shipped `false`.)
 *
 * ⛔ **"PER ROUND" IS THE HOST'S OWN TURN CYCLE AND NOT THE VISITOR'S TURN.**
 * A cap on the visitor's turn would bite only when one visitor sends two visits
 * to the same host in one turn, which is reachable at two seats alone, and four
 * seats is the only seat count that breaches the band. The latch therefore lives
 * on the SEAT (`PlayerState.hostDrewThisRound`) and is cleared when that seat's
 * own turn begins, not on `TurnState`, which turn end replaces wholesale.
 *
 * ⚠️ It is a SECOND leaf and never a re-pointing of `hostDrawOnVisit`, which
 * keeps meaning cards per payment. See the knob's own description for why.
 */
export function hostDrawCapPerRound(data: GameData): boolean {
  return data.rules.turn.hostDrawCapPerRound;
}

/**
 * ⭐ HOW MANY CARDS A HOST DRAWS AT THIS SEAT COUNT, AND THIS IS THE ONE
 * SPELLING EVERY RULE MUST ASK IN (the engine, the bots and the sim alike).
 *
 * ⛔ **THE PRECEDENCE RULE, WRITTEN ONCE AND NOWHERE ELSE: A NON-NULL SLOT IN
 * `hostDrawOnVisitBySeats` WINS; A NULL SLOT DEFERS TO THE SCALAR
 * `hostDrawOnVisit`; AN ABSENT SEAT COUNT DEFERS TO THE SCALAR TOO.** Every slot
 * ships null, so the map changes nothing until somebody sets one, and
 * `overlays/notice-board-visit-host-draw-v1.overlay.json` - which sets the
 * scalar and no slot - still pays 1 at every seat count exactly as it did when
 * it was measured.
 *
 * ⛔ **`hostDrawOnVisit` IS THE BASE AND IS NOT THE ANSWER.** A rule that reads
 * the scalar directly is asking "what does the map say" with the map switched
 * off, which is right until the day somebody sets a slot and then silently
 * wrong. The scalar accessor is kept because the base value is a real thing to
 * read - a knob description, a report header - but **no branch of play may read
 * it.**
 *
 * ⚠️ Its reason for existing is in the knob's own description: capping the
 * faucet was measured on 11/09/2026 and failed, because the bonus rate is nearly
 * insensitive to the faucet's SIZE. Turning it off where there is no headroom is
 * what is left.
 */
export function hostDrawOnVisitAt(data: GameData, seats: number): number {
  return data.rules.turn.hostDrawOnVisitBySeats[String(seats)] ?? data.rules.turn.hostDrawOnVisit;
}

/**
 * Is DEAN'S VARIANT of 09/09/2026 live - the commons' Harvest turned into a
 * free draw of a whole pile to hand? See `rules.turn.commonsTake` and
 * `CommonsTake` for the ruling in full.
 *
 * ⭐ DEFAULTS FALSE. Meaningless outside the commons, but this does not gate on
 * `isCommons` itself, on the same reasoning as `isMeepleAsCard`: the knob can
 * never be `'bonus'` while `visitCurrency` is anything but `'commons'` in
 * practice, because only `overlays/commons-take-to-hand-v1.overlay.json`
 * touches it and it sets `visitCurrency: 'commons'` in the same breath.
 * Callers that already know they are in the commons may read this directly;
 * callers that do not should check `isCommons` first.
 */
export function isCommonsTakeToHand(data: GameData): boolean {
  return data.rules.turn.commonsTake === 'bonus';
}

/**
 * Is DEAN'S 'spend' VARIANT of 09/09/2026 live - the SAME free `commonsTake`
 * move as `isCommonsTakeToHand`, but resolved per-board (orchard to hand,
 * wheat to barn, dairy/vegetable/apiary paid or sown from the pile) rather
 * than always to hand? See `rules.turn.commonsTake` and `CommonsTake` for the
 * ruling in full.
 *
 * ⭐ DEFAULTS FALSE, on the same reasoning `isCommonsTakeToHand` gives: only
 * `overlays/commons-take-to-spend-v1.overlay.json` touches this knob and it
 * sets `visitCurrency: 'commons'` in the same breath, so the knob can never be
 * `'spend'` while `visitCurrency` is anything but `'commons'` in practice.
 * Callers that already know they are in the commons may read this directly;
 * callers that do not should check `isCommons` first. Kept as its own helper
 * rather than folded into `isCommonsTakeToHand` so a caller can tell the two
 * apart without re-reading the knob's raw string.
 */
export function isCommonsTakeToSpend(data: GameData): boolean {
  return data.rules.turn.commonsTake === 'spend';
}

/**
 * Is DEAN'S 'paid' VARIANT of 09/09/2026 live - the SAME free-shaped
 * `commonsTake` move as `isCommonsTakeToHand` (a whole pile, straight to
 * hand), except the take now costs one card of the taker's own, discarded to
 * its own suit's pile? See `rules.turn.commonsTake` and `CommonsTake` for the
 * ruling in full.
 *
 * ⭐ DEFAULTS FALSE, on the same reasoning the other two give: only
 * `overlays/commons-take-paid-v1.overlay.json` touches this knob and it sets
 * `visitCurrency: 'commons'` in the same breath. Callers that already know
 * they are in the commons may read this directly; callers that do not should
 * check `isCommons` first.
 */
export function isCommonsTakePaid(data: GameData): boolean {
  return data.rules.turn.commonsTake === 'paid';
}

/**
 * Is DEAN'S 'coins' VARIANT of 10/09/2026 live - the commons with coins, K3/K4
 * of `docs/commons-coins-handoff-2026-09-10-v2.md`? Under it the bonus slot's
 * second option is *"discard every card on one central pile to their suits'
 * discard piles and take ONE COIN PER CARD"*: no card is paid, the pile leaves
 * the game rather than reaching anybody, and Harvest never reaches the centre
 * (K4, reversing C5).
 *
 * ⭐ DEFAULTS FALSE, on the same reasoning the other three give: only
 * `overlays/commons-coins-v1.overlay.json` and its two sub-arms touch this
 * knob and each of them sets `visitCurrency: 'commons'` in the same breath.
 * Callers that already know they are in the commons may read this directly;
 * callers that do not should check `isCommons` first.
 *
 * ⛔ IT IS THE ONLY `commonsTake` VALUE THAT MINTS A CURRENCY, so it is also
 * the gate on the arm's two coin sinks: `farmsteadCoinPower` and
 * `endgameCoinCost` are meaningless without it, because nothing else in the
 * game produces a coin.
 */
export function isCommonsTakeCoins(data: GameData): boolean {
  return data.rules.turn.commonsTake === 'coins';
}

/**
 * Does a `commonsTake` send the pile OUT OF THE GAME rather than to a player?
 * True under `'coins'` alone, where the pile is discarded to its cards' own
 * suit discards and the taker is paid in a currency instead.
 *
 * ⭐ IT IS THE COUNTERPART OF `commonsTakeGoesToHand` AND DELIBERATELY NOT PART
 * OF IT. Every earlier take handed the cards to somebody - `'bonus'` and
 * `'paid'` to the hand, `'spend'` to whatever the board's action used - and all
 * three ran the bonus at 74% to 89% of turns, because the cards taken paid for
 * the next play. This one hands back nothing playable, which is the whole
 * design difference, so a caller asking "where do the cards go" must be able to
 * tell the two apart in one read.
 */
export function commonsTakeLeavesTheGame(data: GameData): boolean {
  return isCommonsTakeCoins(data);
}

/**
 * Does HARVEST still reach the centre? False under every `commonsTake` value
 * but the shipped `'harvest'`, which is C5 - own full building OR any non-empty
 * central pile, into the barn.
 *
 * ⭐ ONE SPELLING FOR "the wheat board is offered only when the seat already has
 * a full building", which four separate rules now say and which the farm-bypass
 * reading depends on: under `'bonus'`, `'spend'` and `'paid'` the centre empties
 * through the `commonsTake` move instead (D-S4), and under `'coins'` it empties
 * to the discards (K4). In every one of those the centre-to-barn share reads 0%
 * BY CONSTRUCTION, and a reader who does not know that will mistake a structural
 * zero for a fixed problem.
 *
 * ⚠️ `commonsHarvestMin` and `commonsHarvestTake` have no subject whenever this
 * is false: there is no central harvest left for either of them to ration.
 */
export function commonsHarvestReachesCentre(data: GameData): boolean {
  return data.rules.turn.commonsTake === 'harvest';
}

/**
 * Is the WILD PAIR built (D5/D7 of the commons pass, ruled back in by K3 on
 * 10/09/2026) - two cards of any colours paying for one board of any colour,
 * both landing on its pile?
 *
 * ⭐ DEFAULTS FALSE, AND THAT IS ALSO HOW THE COLOUR-MATCH ARM WAS MEASURED. D5
 * described the pair and D7 recorded that the 09/09/2026 arm shipped without it,
 * so that arm's 34.4% of turns is the colour rule at its HARSHEST and the rule
 * Dean would write reads somewhere between it and the shipped 58.9%.
 *
 * ⚠️ MEANINGLESS WITHOUT `rules.economy.commonsColourMatch`, unlike the
 * `commonsTake` predicates above: with any card already paying for any board
 * there is no colour for a pair to stand in for. A caller must read both.
 */
export function commonsWildPair(data: GameData): boolean {
  return data.rules.economy.commonsWildPair;
}

/**
 * What an Endgame card costs in COINS, or null for the shipped card price of two
 * cards of its own suit (K15, Dean 10/09/2026). The arm sets 3.
 *
 * ⛔ THE PRICE IS A RULES KNOB AND NEVER A CARD FIELD. `Card.buildCost` has
 * exactly `suit` and `wild`; the coin third of it went with the currency on
 * 02/09/2026, and a coin price arriving from a re-extract rather than from a
 * ruling is exactly the drift `data.test.ts` guards against.
 *
 * ⚠️ Read only under `isCommonsTakeCoins`, which is the only thing that mints a
 * coin: a price in a currency nobody can earn is a card nobody can build.
 */
export function endgameCoinCost(data: GameData): number | null {
  return data.rules.economy.endgameCoinCost;
}

/**
 * Is the Farmstead a COIN-ACTIVATED SUIT POWER (K10-K14, Dean 10/09/2026)? True
 * makes it a building with no threshold whose activation cost is one coin, used
 * as a GROW that is your MAIN action, once per turn, with nothing placed on it,
 * and its own end-game scorer moved to the BARN (K13) rather than deleted.
 *
 * ⛔ NO RENT (K14): a rival can never use your Farmstead.
 *
 * ⚠️ Read only under `isCommonsTakeCoins`, for the same reason
 * `endgameCoinCost` is: it is the second of the arm's two sinks and nothing
 * else in the game produces a coin to spend on it.
 */
export function farmsteadCoinPower(data: GameData): boolean {
  return data.rules.economy.farmsteadCoinPower;
}

/**
 * ⭐ Is the own-crop end-game scorer printed on the BARN rather than the
 * Farmstead (Dean, 13/09/2026)? See the note on the type. Score-neutral under
 * the commons; not neutral under the coins arm, which pins it false.
 */
export function cropScorerOnBarn(data: GameData): boolean {
  return data.rules.economy.cropScorerOnBarn;
}

/**
 * ⭐ THE VILLAGE STORE'S MINT, AND THERE IS EXACTLY ONE (V1, Dean 12/09/2026,
 * A150): coins taken per ADDITIONAL barn card spent at a delivery. One accessor,
 * so "what does a converted card pay" is asked in exactly one spelling across
 * the engine, the bots and the sim.
 *
 * ⛔ 0 IS THE SHIPPED VALUE AND IT IS THE WHOLE OFF SWITCH: nothing in the game
 * mints a coin. Every coin economy this project has had died of a SECOND faucet
 * or a pity rate, so this being the only mint is a property to preserve.
 *
 * The rule: the cards are spent FROM THE BARN (V2) and the exchange resolves
 * AFTER the crate is paid (V3), so a player can never convert the cards the
 * delivery itself needs. ⛔ And it must not be built as a subset enumeration -
 * see `rules.economy.storeCoinsPerCard` for the power-set trap and the repeated
 * binary choice that avoids it.
 *
 * ⚠️ `coinEconomy()` in `packages/engine/src/setup.ts` must be extended to
 * include this above 0, or the wallet will not exist when the Store is on.
 */
export function storeCoinsPerCard(data: GameData): number {
  return data.rules.economy.storeCoinsPerCard;
}

/**
 * ⭐ THE SHARED COIN SUPPLY, PER SEAT (V4, Dean 12/09/2026, A150). The pool is
 * this times the number of players: the arm's 5 is 10 coins at two seats and 20
 * at four, shared, with NO per-player holding cap, and spent coins return to it
 * (V5).
 *
 * Shipped 0, which is inert twice over: there is no pool, and with
 * `storeCoinsPerCard` also 0 there is nothing to put in one.
 *
 * ⭐ THE BOUND IS WHAT MAKES THE MINT SAFE: never more than this times seats
 * conversions exist in the whole game, however big a barn gets.
 *
 * ⚠️ Left as a per-seat number rather than a resolved pool because seats are not
 * a property of `GameData`; the multiplication belongs to whoever knows the seat
 * count, exactly as `meeplesDealt(data, seats)` does it.
 */
export function coinSupplyPerPlayer(data: GameData): number {
  return data.rules.economy.coinSupplyPerPlayer;
}

/**
 * ⭐ MAY A COIN PAY A BUILD COST (V6, Dean 12/09/2026, A150)? Shipped false, and
 * meaningless where nothing mints a coin. Power and Endgame cards are included
 * (V7), so two coins buys one.
 *
 * ⛔ SEPARATE FROM `coinPaysGrow` BECAUSE THEY ARE TWO DIFFERENT BETS: Build
 * converts barn into tableau, Grow converts barn into repeatable abilities. An
 * arm that bundles them cannot say which one moved the numbers.
 *
 * ⚠️ It is the branching risk of the package: coins must enter the payment
 * enumerator as a COUNT and never as a choice of which coins, because they are
 * fungible.
 */
export function coinPaysBuild(data: GameData): boolean {
  return data.rules.economy.coinPaysBuild;
}

/**
 * ⭐ MAY A COIN PAY A BUILD COST'S n-OF-SUIT REQUIREMENT, and not only its wild
 * slots (the second half of V6, Dean 12/09/2026)? Shipped false. Three coins
 * paying "2 apples and a wild" is this leaf and not `coinPaysBuild`.
 *
 * ⛔ READ IT WITH `coinPaysBuild`, NEVER INSTEAD OF IT: a coin that pays a suit
 * requirement but not a build is not a rule anybody has proposed. The split
 * exists because "coins pay wild costs only" and "coins pay everything" are
 * meaningfully different games and it is one run to find out.
 *
 * ⭐ It is also the first thing proposed that pushes against the monoculture
 * pull, so the own-crop build share (near 83% since v31) is a reading this leaf
 * owns rather than a background number.
 */
export function coinPaysSuitCost(data: GameData): boolean {
  return data.rules.economy.coinPaysSuitCost;
}

/**
 * ⭐ MAY A COIN PAY A GROW'S ACTIVATION (V8, Dean 12/09/2026, A150)? Shipped
 * false. ⛔ THE COIN PLACES NOTHING, so the building does not advance toward its
 * threshold and never clogs, placement triggers do not fire (A16) and A21 does
 * not count a building held empty this way - but the building's "when activated"
 * ability DOES fire, because that is the whole point of a Grow (D5).
 *
 * ⚠️ Whether a FULL building is a legal target is a second question and a second
 * leaf: ask `coinGrowReachesFullBuildings`, never `coinGrowOnFullBuilding`.
 */
export function coinPaysGrow(data: GameData): boolean {
  return data.rules.economy.coinPaysGrow;
}

/**
 * The BASE value of V9: may a coin-Grow target a full building?
 * (`rules.economy.coinGrowOnFullBuilding`, shipped false.)
 *
 * ⛔ **THIS IS NOT THE ANSWER AND NO BRANCH OF PLAY MAY READ IT.** Ask
 * `coinGrowReachesFullBuildings(data)`, which carries the precedence. This
 * accessor is kept for the same reason `hostDrawOnVisit` is kept beside
 * `hostDrawOnVisitAt`: the base value is a real thing to read in a knob
 * description or a report header, and nowhere else.
 */
export function coinGrowOnFullBuilding(data: GameData): boolean {
  return data.rules.economy.coinGrowOnFullBuilding;
}

/**
 * ⭐ CAN A COIN-GROW REACH A FULL BUILDING RIGHT NOW, AND THIS IS THE ONE
 * SPELLING EVERY RULE MUST ASK IN (the engine, the bots and the sim alike).
 *
 * ⛔ **THE PRECEDENCE RULE, WRITTEN ONCE AND NOWHERE ELSE: V9 IS MEANINGLESS
 * WITHOUT V8.** A full-building Grow that no coin can pay for is not a rule at
 * all, so `coinGrowOnFullBuilding` answers true here only when `coinPaysGrow` is
 * also on. A check that reads the raw leaf is right until somebody runs
 * `overlays/village-store-coins-build-only-v1.overlay.json` and then silently
 * wrong, which is the `hostGift` seam of 12/09/2026 - a term reading a rule off
 * the wrong accessor and pricing a decision that could not happen.
 *
 * ⭐ WHAT IT TURNS ON IS THE STRONGEST CLAUSE IN THE PACKAGE: the first clog
 * bypass in this game since the meeples, ruled in deliberately (Dean,
 * 12/09/2026). ⚠️ A MEEPLE GROW IS THE OPPOSITE and the two differ on purpose
 * (M8): it places its activation card as normal and CAN clog.
 *
 * ⚠️ `isFull` and `isHarvestable` stopped being the same boolean on 10/09/2026
 * (S8), so the caller still has to decide which one a Grow's legality wants.
 * This function answers whether the RULE is on, never whether a given building
 * qualifies.
 */
export function coinGrowReachesFullBuildings(data: GameData): boolean {
  return data.rules.economy.coinPaysGrow && data.rules.economy.coinGrowOnFullBuilding;
}

/**
 * Does a `commonsTake` land its pile in the taker's HAND? True under both
 * `'bonus'` (free) and `'paid'` (one card discarded first) - the two values
 * whose take is an uncomplicated whole-pile move to hand, told apart only by
 * whether it costs anything. FALSE under `'spend'`, where the destination
 * depends on which board is taken (orchard to hand, wheat to barn, the rest
 * elsewhere) and no single answer is correct.
 *
 * ⛔ AND FALSE UNDER `'coins'` (10/09/2026), WHICH IS THE ONE A FUTURE SESSION
 * IS MOST LIKELY TO ADD BY REFLEX. A coin take hands back no cards at all: the
 * pile is discarded to its cards' own suit piles and the taker is paid in a
 * currency, so nothing arrives in the hand and adding `'coins'` here would put
 * cards into a hand that never got any. `commonsTakeLeavesTheGame` is its
 * predicate.
 *
 * Use this where the DESTINATION is what a caller cares about; use
 * `isCommonsTakeToHand` or `isCommonsTakePaid` directly where the caller
 * needs to tell the two apart (for instance, whether a fee is owed).
 */
export function commonsTakeGoesToHand(data: GameData): boolean {
  return isCommonsTakeToHand(data) || isCommonsTakePaid(data);
}

/**
 * Is R15 live - a meeple spendable as a card of its colour? See
 * `rules.turn.meepleAsCard`.
 *
 * ⭐ DEFAULTS FALSE. The knob is meaningless outside the meeple loop, but this
 * does not gate on `isMeepleCurrency` itself - the data can never set
 * `meepleAsCard` true while `visitCurrency` is `'card'` in practice, because
 * only handoff-v2 overlays touch it and they all set `visitCurrency: 'meeple'`
 * in the same breath. Callers that already know they are in the meeple arm may
 * read this directly; callers that do not should check `isMeepleCurrency`
 * first.
 */
export function isMeepleAsCard(data: GameData): boolean {
  return data.rules.turn.meepleAsCard;
}

/**
 * The amended R6 slot price, or null for the v1 block. See
 * `rules.turn.slotToll`.
 *
 * null: a slot holding any meeple is BLOCKED and refuses that colour outright.
 * A number n: nothing is ever refused, and visiting a slot already holding k
 * meeples costs n * k extra meeples of any colours - the toll - on top of the
 * acting meeple, boxed rather than handed to the host.
 */
export function slotTollOf(data: GameData): number | null {
  return data.rules.turn.slotToll;
}

/**
 * ⭐ R17: does a meeple spent as a CARD land on a neighbour's board rather
 * than in the box? Only ever true when `meepleAsCard` is on as well - there is
 * nothing to place when a meeple cannot pay for anything.
 */
export function meepleAsCardGoesToBoard(data: GameData): boolean {
  return data.rules.turn.meepleAsCard && data.rules.turn.meepleAsCardGoesTo === 'board';
}

/** The FLAT toll for placing a paid meeple onto an occupied slot (R17). */
export function paymentSlotTollOf(data: GameData): number {
  return data.rules.turn.paymentSlotToll;
}

/**
 * How many meeples one tile is seeded with at setup.
 *
 * ⭐ **DERIVED FROM `tileMeepleSpaces` SINCE 12/09/2026 (A151) AND NO LONGER A
 * RULE OF ITS OWN.** It used to carry the whole seeding rule and
 * `meepleIndexForSpace` carried a second copy of it, and the two DISAGREED
 * about `visitCurrency: 'noticeBoardPower'`: this function answered 0 while
 * that one answered the identity, so a game seeding nothing still claimed a
 * meeple lived at index 0. It was harmless only while nothing seeded a meeple
 * under that currency, which is exactly what M1's `deliveryMeepleSpace` changes.
 * Both are now one line over one list, so a fifth `visitCurrency` cannot answer
 * one thing here and another there.
 *
 * Under `'meeple'` it is the length of `island.meeples.seededSpaces` - `[1]`,
 * the 3 VP second delivery - because the rule names WHICH spaces carry one
 * rather than how many each carries, and which is the whole of the design: being
 * first to a tile is 6 VP flat, being second is 3 VP plus a stored action. Under
 * the `'card'` control it is every delivery space times `perDeliverySpace`,
 * exactly as v31 dealt them, which is twice as deep a draw from the same bag.
 */
/**
 * ⭐ What the Dairy Notice Board does after its Build (Dean, 12/09/2026).
 * Shipped 'none'. Read only under visitCurrency 'noticeBoardPower'.
 */
export function dairyGrowsBuilt(data: GameData): 'none' | 'paid' | 'paidWild' | 'free' {
  return data.rules.economy.noticeBoardPower.dairyGrowsBuilt;
}

export function meeplesPerTile(data: GameData): number {
  return tileMeepleSpaces(data).length;
}

/**
 * Which entry of a tile's `meeples` array belongs to delivery space `space`, or
 * -1 for a space that carries no meeple.
 *
 * ⭐ THE ARRAY IS DENSE AND THE SPACES ARE NOT, which is the whole reason this
 * function exists. Under `'card'` every space has a meeple and the mapping is
 * the identity; under `'meeple'` only the seeded spaces do, and a tile holding
 * one meeple for space 1 stores it at index 0 - a sparse array would not survive
 * a JSON round-trip through a capture, and a nullable one would push the hole
 * into every reader.
 *
 * ⛔ **IT IS `indexOf` OVER `tileMeepleSpaces` AND NEVER THE IDENTITY AGAIN**
 * (12/09/2026, A151). The old `if (!isMeepleCurrency(data)) return space;`
 * answered the identity for the notice-board visit, which seeds NO meeples, so
 * the two functions described different games; and it would have answered "index
 * 1" for M1's tile, whose single meeple is stored densely at index 0. The
 * identity was only ever right at `perDeliverySpace: 1`, and this says so by
 * construction rather than by coincidence.
 */
export function meepleIndexForSpace(data: GameData, space: number): number {
  return tileMeepleSpaces(data).indexOf(space);
}

/**
 * The BASE value of M1: which delivery space carries a meeple at setup
 * (`rules.turn.deliveryMeepleSpace`, shipped `null`).
 *
 * ⛔ **THIS IS NOT THE ANSWER AND NO BRANCH OF PLAY MAY READ IT.** Ask
 * `tileMeepleSpaces(data)`, which carries the precedence. Kept for the same
 * reason `hostDrawOnVisit` is kept beside `hostDrawOnVisitAt`: a knob
 * description and a report header are real things to read, and nothing else is.
 *
 * ⛔ AND `null` DOES NOT MEAN "NO MEEPLES" - it means "defer to the seeding this
 * game already does", which is `tileMeepleSpaces`' null branch. A reader who
 * takes the raw null for "none" has the rule backwards.
 */
export function deliveryMeepleSpace(data: GameData): number | null {
  return data.rules.turn.deliveryMeepleSpace;
}

/**
 * ⭐ WHICH DELIVERY SPACES OF ONE TILE CARRY A MEEPLE AT SETUP, AND THIS IS THE
 * ONE SPELLING EVERY RULE MUST ASK IN. One entry per meeple, so a space seeded
 * twice appears twice and `.length` is the count.
 *
 * ⛔ **THE PRECEDENCE RULE, WRITTEN ONCE AND NOWHERE ELSE: A NON-NULL
 * `rules.turn.deliveryMeepleSpace` WINS OUTRIGHT AND SEEDS EXACTLY ONE MEEPLE ON
 * THAT SPACE; `null` DEFERS ENTIRELY TO THE EXISTING `meeplesPerTile` SEEDING.**
 * `null` is the shipped value and it is NOT "no meeples": the commons and the
 * notice-board visit seed none, the v31 control seeds one per delivery space and
 * the meeple loop seeds `island.meeples.seededSpaces`. M1's `1` is the 3 VP
 * second delivery and never index 0.
 *
 * ⛔ **AN OUT-OF-RANGE OVERRIDE SEEDS NOTHING RATHER THAN THROWING**, matching
 * the filter `meeplesPerTile` already applies to `seededSpaces`: the knob is a
 * free integer, and a tile has only `deliveriesPerTile` spaces.
 *
 * ⭐ **AND SINCE 12/09/2026 IT IS THE ONLY SEEDING RULE IN THE PACKAGE.**
 * `meeplesPerTile` is `.length` of this and `meepleIndexForSpace` is `indexOf`
 * over it, so the three cannot drift. They had already drifted: those two
 * disagreed about `visitCurrency: 'noticeBoardPower'`, one answering "no
 * meeples" and the other the identity mapping, which was harmless only while
 * nothing seeded a meeple there - the precise thing M1 changes.
 */
export function tileMeepleSpaces(data: GameData): readonly number[] {
  const spaces = deliveriesPerTile(data);
  const only = data.rules.turn.deliveryMeepleSpace;
  if (only !== null) return only >= 0 && only < spaces ? [only] : [];
  // ⛔ THE COMMONS SEEDS NONE (09/09/2026, C6) AND SO DOES THE NOTICE-BOARD
  // VISIT (10/09/2026, §2.6 of its handoff). Answered before the meeple branch
  // on purpose: neither is a meeple currency, so a fifth `visitCurrency` falling
  // through to the `'card'` arithmetic below would seed two a tile without a
  // word of warning. ⚠️ It is answered AFTER the override, because M1 seeds a
  // meeple in whatever game the arm is stacked on and the override wins outright.
  if (isCommons(data) || isNoticeBoardPower(data)) return [];
  // The meeple loop names WHICH spaces carry one: `[1]`, the 3 VP second
  // delivery. Out-of-range entries are filtered rather than thrown on, which is
  // what the count has always done.
  if (isMeepleCurrency(data)) {
    return data.island.meeples.seededSpaces.filter((i) => i >= 0 && i < spaces);
  }
  // The v31 control: every delivery space, `perDeliverySpace` times each. ⚠️ The
  // ORDER is what `meepleIndexForSpace` reads, and at the shipped
  // `perDeliverySpace: 1` it is the identity the old code hardcoded. At 2 it
  // would be [0, 0, 1, 1] and the identity would be wrong, which is the second
  // reason the mapping is derived here rather than assumed there.
  const seeded: number[] = [];
  for (let space = 0; space < spaces; space += 1) {
    for (let n = 0; n < data.island.meeples.perDeliverySpace; n += 1) seeded.push(space);
  }
  return seeded;
}

/**
 * ⭐ WHEN A HELD MEEPLE MAY BE SPENT (M4, Dean 12/09/2026, A151). One accessor,
 * so "which phase is the meeple spend" is asked in one spelling.
 *
 * ⛔ **`'start'` IS THE SHIPPED VALUE AND IT IS THE CURRENT BEHAVIOUR, NOT AN
 * OFF SWITCH.** The v31 control spends meeples at the start of the turn
 * (`meepleOptions` in the engine, and `turnflow.ts`'s own header) and
 * `packages/sim/fixtures/2p-v31-opening.json` replays against it, so `'none'`
 * would delete a live phase rather than change nothing. `'afterAction'` is M4's
 * arm: the spend moves to after the main action, the meeple buys the PLAIN
 * action of its colour, and it then leaves the game.
 */
export function meepleSpendTiming(data: GameData): MeepleSpendTiming {
  return data.rules.turn.meepleSpendTiming;
}

/**
 * ⭐ HOW MANY MEEPLES ONE SEAT MAY SPEND IN A TURN (M5, Dean 12/09/2026, A151),
 * or `null` for UNLIMITED, which is the shipped value and the game as it plays
 * today.
 *
 * ⛔ **`null` IS "NO RULE HERE" AND `0` WOULD BE "NO SPEND AT ALL".** That is the
 * established idiom of `commonsThreshold`, `commonsHarvestTake` and
 * `meepleCapPerColour`, and it is why this ships null rather than the 0 the
 * build handoff's table asked for: there is no per-turn cap in the game today,
 * so 0 would delete the v31 control's phase.
 *
 * ⚠️ The arm is 1, which is Dean's ruling, and C112 asks for it to be run
 * against `meepleSpendDistinctColours` instead. The two are orthogonal leaves.
 */
export function meepleSpendPerTurn(data: GameData): number | null {
  return data.rules.turn.meepleSpendPerTurn;
}

/**
 * ⭐ C112'S ALTERNATIVE TO THE PER-TURN CAP: may no two meeples spent in one
 * turn share a colour? Shipped `false`, which is inert because no such
 * restriction exists today.
 *
 * ⛔ A SECOND LEAF RATHER THAN A MAGIC VALUE OF `meepleSpendPerTurn`, because
 * "no two of the same colour" is not expressible as an integer and because
 * re-pointing a published quantity at a rule of a different shape is a mistake
 * this project has paid for twice (a17 on 09/09/2026, the meeple cap on
 * 05/09/2026). `meepleSpendPerTurn` keeps meaning HOW MANY; this says WHICH ONES
 * MAY BE COMBINED.
 *
 * ⚠️ The two arms C112 wants are one run apart: the rule as ruled is
 * `meepleSpendPerTurn` 1 with this false, and the variant is
 * `meepleSpendPerTurn` null with this true. The cap of 1 removes exactly the
 * combo burst Dean's own table enjoyed on 11/09/2026, which is why the
 * alternative has to be measured rather than argued.
 */
export function meepleSpendDistinctColours(data: GameData): boolean {
  return data.rules.turn.meepleSpendDistinctColours;
}

/** Cards actually in the game: the enable flag applied. */
export function activeCards(data: GameData = BASE_GAME_DATA) {
  return data.cards.catalogue.filter((card) => card.enabled);
}

/**
 * Total barn cards a tile costs: one demand per crate, each paid in
 * `cardsPerCrate` cards. Derived rather than stored, so a knob on either factor
 * moves the real cost instead of half of it. No level argument since the flat
 * island - every tile costs the same.
 */
export function deliveryCost(data: GameData): number {
  const { crates, cardsPerCrate } = data.island.tileRule;
  return crates * cardsPerCrate;
}

/** How many deliveries one tile accepts. The VP schedule's length IS the rule. */
export function deliveriesPerTile(data: GameData): number {
  return data.island.vpByDeliveryOrder.length;
}

/**
 * VP the next delivery to a tile with `already` receipts on it would take. 0
 * past the end of the schedule, which is also the tile being full - callers
 * check capacity, this never invents a value for an illegal delivery.
 */
export function deliveryVp(data: GameData, already: number): number {
  return data.island.vpByDeliveryOrder[already] ?? 0;
}
